#! /bin/sh

# MIT License
#
# Copyright (c) 2017 Josef Friedrich <josef@friedrich.rocks>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

_short_description() {
	echo 'A short description of what this command does.'
}

_usage() {
	echo "Usage: This is a example script

$(_short_description)

Options:
	-h, --help
	  Show this help message
	-s, --short-description
	  Show a short description / summary"
}

_getopts() {
	while getopts ':hs-:' OPT ; do
		case $OPT in
			h) _usage ; exit 0 ;;
			s) _short_description ; exit 0 ;;
			-)
				case $OPTARG in
					help) _usage ; exit 0 ;;
					short-description) _short_description ; exit 0 ;;
					'') break ;;
					*) echo "Invalid option “--$OPTARG”!" >&2 ; exit 2 ;;
				esac ;;
			\?) echo "Invalid option “-$OPTARG”!" >&2 ; exit 2 ;;
			*) _usage ; exit 2 ;;
		esac
	done
}

## This SEPARATOR is required for test purposes. Please don’t remove! ##

_getopts $@
